app-config:
  llm: 'mistralai/Mixtral-8x7B-Instruct-v0.1'
  huggingface-hub-token: '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'
  device: 'cpu'
  show-explanation: true
  split-on-sentences: true
  log-prompts: false
  log-llm-responses: false
