app-config:
  llm: 'mistralai/Mistral-7B-Instruct-v0.2'
  huggingface-hub-token: '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'
  device: 'cpu'
  split-on-sentences: true
  log-prompts: false
  log-llm-responses: false
